authentication/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import RegistrationView, UsernameValidationView, EmailValidationView, VerificationView, LoginView, LogoutView
from django.views.decorators.csrf import csrf_exempt

app_name = "authentication"

urlpatterns = [
    path('register', RegistrationView.as_view(), name="register"),
    path('login', LoginView.as_view(), name="login"),
    path('logout', LogoutView.as_view(), name="logout"),
    path('validate-username', csrf_exempt(UsernameValidationView.as_view()), name="validate-username"),
    path('validate-email', csrf_exempt(EmailValidationView.as_view()), name='validate_email'),
    path('activate/<uidb64>/<token>', VerificationView.as_view(), name='activate') 
]

expenses/urls.py
from django.views.decorators.csrf import csrf_exempt
from django.urls import path
from .views import index, add_expense, expense_edit, delete_expense, search_expenses, expense_category_summary, stats_view, export_csv 




urlpatterns = [
    path('', index, name='expenses'),
    path('add-expense', add_expense, name='add-expenses'),
    path('edit-expense/<int:id>', expense_edit, name="expense-edit"),
    path('expense-delete/<int:id>', delete_expense, name="expense-delete"),
    path('stats-view', stats_view, name="stats_view"),
    path('search-expenses', csrf_exempt(search_expenses), name="search_expenses"),
    path('expense-category-summary', csrf_exempt(expense_category_summary), name="expense_category_summary"),
    path('export-csv', export_csv, name="export_csv"),
]

iemanager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('expenses.urls')),
    path('authentication/', include('authentication.urls')),
    path('preferences/', include('userpreferences.urls')),
    path('income/', include('userincome.urls'))
]

authentication/models.py
from django.db import models

# Create your models here.

authentication/views.py
import json

from django.contrib import messages
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.contrib import auth
from django.contrib.sites.shortcuts import get_current_site
from django.core.validators import validate_email
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.encoding import force_bytes, force_text, DjangoUnicodeDecodeError
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views import View

from .utils import account_activation_token




class EmailValidationView(View):
    def post(self, request):
        data = json.loads(request.body)
        email = data['email']
        try: 
            validate_email(email)
        except:
            return JsonResponse({'email_error': 'Email is invalid'}, status=400)
        if User.objects.filter(email=email).exists():
            return JsonResponse({'email_error': 'sorry email in use, choose another one '}, status=409)
        return JsonResponse({'email_valid': True})


class UsernameValidationView(View):
    def post(self, request):
        data = json.loads(request.body)
        username = data['username']
        if not str(username).isalnum():
            return JsonResponse({'username_error': 'username should only contain alphanumeric characters'}, status=400)
        if User.objects.filter(username=username).exists():
            return JsonResponse({'username_error': 'sorry username in use,choose another one '}, status=409)
        return JsonResponse({'username_valid': True})

class RegistrationView(View):
    def get(self, request):
        return render(request, 'authentication/register.html')


    def post(self, request):
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')

        context = {
            'fieldValues': request.POST
        }

        if not User.objects.filter(username=username).exists():
            if not User.objects.filter(email=email).exists():
                if len(password) < 6:
                    messages.error(request, 'Your password is too short.')
                    return render(request, 'authentication/register.html', context)

                user = User.objects.create(username=username, email=email)
                user.set_password(password)
                user.is_active = False
                user.save()

                email_subject = 'Activate your account'

                current_site = get_current_site(request)
                email_body = {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user)
                }

                link = reverse('authentication:activate', kwargs={
                                                    'uidb64': email_body['uid'],
                                                    'token': email_body['token']
                })

                activate_url= 'http://'+current_site.domain+link

                email = EmailMessage(
                    email_subject,
                    'Hi' +user.username+ ', Please go to the link below to activate your account. \n' +activate_url,
                    'noreplay@mymail.com',
                    [email],
                )
                email.send(fail_silently=False)

                messages.success(request, 'Account created successfully.')
                return render(request, 'authentication/register.html')

        return render(request, 'authentication/register.html', context)


class VerificationView(View):
    def get(self, request, uidb64, token):
        try:
            id = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=id)

            if not account_activation_token.check_token(user, token):
                return redirect('login'+'?message='+'User already activated')

            if user.is_active:
                return redirect('login')
            user.is_active = True
            user.save()

            messages.success(request, 'Account activated successfully')
            return redirect('login')

        except Exception as ex:
            pass

        return redirect('login')


class LoginView(View):
    def get(self, request):
        return render(request, 'authentication/login.html')

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']

        if username and password:
            user = auth.authenticate(username=username, password=password)

            if user:
                if user.is_active:
                    auth.login(request, user)
                    messages.success(request, 'Welcome, ' + user.username+' you are now logged in')
                    return redirect('expenses')
                messages.error(
                    request, 'Account is not active,please check your email')
                return render(request, 'authentication/login.html')
            messages.error(
                request, 'Invalid credentials,try again')
            return render(request, 'authentication/login.html')
            
        messages.error(
            request, 'Please fill all fields')
        return render(request, 'authentication/login.html')



class LogoutView(View):
    def post(self, request):
        auth.logout(request)
        messages.success(request, 'You have been logged out')
        return redirect('authentication:login')

templates/authentication/activate_account.html
{% autoescape off %} Hi {{ user.username }}, Please click on the link to confirm
your registration, http://{{ domain }}{% url 'activate' uidb64=uid token=token
%} {% endautoescape %}

templates/authentication/login.html
{% extends 'base_auth.html' %}
{% load static %}


{% block content %}

<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <div class="card mt-5">


      <div class="card-body">
        <div class="card-title py-3">
          <h4>Login to your  account</h4>
        </div>
        <form action="{% url 'authentication:login' %}" method="post">
          {% csrf_token %}

          {% include 'partials/_messages.html' %}
          <div class="form-group">
            <input
              type="text"
              name="username"
              placeholder="username"
              id="usernameField"
              value="{{fieldValues.username}}"
              class="form-control form-control-sm"
            />
          </div>
          <div class="form-group">
            <input
              type="password"
              name="password"
              placeholder="Password"
              class="form-control form-control-sm"
              id="passwordField"
            />
          </div>
          <input type="submit" value="Login" class="btn btn-block btn-primary submit-btn" />
        </form>

      </div>

      </div>
    </div>
  </div>
  <div class="col-md-4"></div>
</div>

<script src="{% static 'js/register.js' %}"></script>

{% endblock content %}

templates/authentication/register.html
{% extends 'base_auth.html' %}
{% load static %}


{% block content %}

<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <div class="card mt-5">


      <div class="card-body">
        
        <div class="card-title py-3">
          <h4>Register for a free account</h4>
        </div>
        <form action="{% url 'authentication:register' %}" method="post">
          {% csrf_token %}

          {% include 'partials/_messages.html' %}
          <div class="form-group">
            <input
              type="text"
              name="username"
              placeholder="username"
              id="usernameField"
              value="{{fieldValues.username}}"
              class="form-control form-control-sm"
            />
          </div>
          <div class="invalid_feedback invalid-feedback" style="display:none">
          </div>
          <p class="text-sm text-success usernameSuccessOutput"></p>
          <div class="form-group">
            <input
              type="email"
              name="email"
              placeholder="Email"
              class="form-control form-control-sm"
              id="emailField"

              value="{{fieldValues.email}}"
            />
          </div>

          <div class="emailFeedBackArea invalid-feedback" style="display:none">
          </div>
          <div class="form-group">
            <input
              type="password"
              name="password"
              placeholder="Password"
              class="form-control form-control-sm"
              id="passwordField"
            />
            <small class="float-right py-3 showPasswordToggle">SHOW</small>
          </div>
          <input type="submit" value="Register" class="btn btn-block btn-primary submit-btn" />
        </form>

      </div>

      </div>
    </div>
  </div>
  <div class="col-md-4"></div>
</div>

<script src="{% static 'js/register.js' %}"></script>

{% endblock content %}

templates/authentication/reset-password.html
{% extends 'base_auth.html' %}


{% block content %}


<div class="card">


<div class="card-body">

<h1>Login</h1>



</div>




</div>
{% endblock content %}

templates/authentication/set-newpassword.html
{% extends 'base_auth.html' %}


{% block content %}


<div class="card">


<div class="card-body">

<h1>Login</h1>



</div>




</div>
{% endblock content %}