authentication/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import RegistrationView, UsernameValidationView, EmailValidationView, VerificationView, LoginView, LogoutView
from django.views.decorators.csrf import csrf_exempt

app_name = "authentication"

urlpatterns = [
    path('register', RegistrationView.as_view(), name="register"),
    path('login', LoginView.as_view(), name="login"),
    path('logout', LogoutView.as_view(), name="logout"),
    path('validate-username', csrf_exempt(UsernameValidationView.as_view()), name="validate-username"),
    path('validate-email', csrf_exempt(EmailValidationView.as_view()), name='validate_email'),
    path('activate/<uidb64>/<token>', VerificationView.as_view(), name='activate') 
]

expenses/urls.py
from django.views.decorators.csrf import csrf_exempt
from django.urls import path
from .views import index, add_expense, expense_edit, delete_expense, search_expenses, expense_category_summary, stats_view, export_csv 




urlpatterns = [
    path('', index, name='expenses'),
    path('add-expense', add_expense, name='add-expenses'),
    path('edit-expense/<int:id>', expense_edit, name="expense-edit"),
    path('expense-delete/<int:id>', delete_expense, name="expense-delete"),
    path('stats-view', stats_view, name="stats_view"),
    path('search-expenses', csrf_exempt(search_expenses), name="search_expenses"),
    path('expense-category-summary', csrf_exempt(expense_category_summary), name="expense_category_summary"),
    path('export-csv', export_csv, name="export_csv"),
]

iemanager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('expenses.urls')),
    path('authentication/', include('authentication.urls')),
    path('preferences/', include('userpreferences.urls')),
    path('income/', include('userincome.urls'))
]

templates/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>InExManager {% block title %} {% endblock %}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet" />
    <link href="{% static 'css/main.css'%}" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet" />
  </head>
  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">InExManager</a>

      <ul
        class="navbar-nav px-3"
        style="display: flex; flex-direction: row; align-items: center;"
      >
        <li class="nav-item text-nowrap">
          <span class="nav-link" href="#">
            {{request.user.username}}
          </span>
        </li>

        <li class="nav-item text-nowrap mt-3 ml-2">
          <form action="{% url  'authentication:logout' %}" method="POST">
            {% csrf_token %}
            <input
              class="text text-capitalize"
              type="submit"
              value="Sign out"
            />
          </form>
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        {% include 'partials/_sidebar.html' %}

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          {% block content %} {% endblock %}
        </main>
      </div>
    </div>

    
    <script>
      setTimeout(function() {
          $('.messages').fadeOut('fast');
      }, 3000);
    </script>

    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script>
      window.jQuery ||
        document.write(
          '<script src="/docs/4.4/static/js/vendor/jquery.slim.min.js"><\/script>'
        );
    </script>
    <script 
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" 
    crossorigin="anonymous">
    </script>

    {% comment %} <script
      src="/docs/4.4/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm"
      crossorigin="anonymous">
    </script> {% endcomment %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>


    {% comment %} <script 
    src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" 
    integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" 
    crossorigin="anonymous"> {% endcomment %}
    
    </script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" 
    integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" 
    crossorigin="anonymous">
    </script> 

    {% comment %} <script src="{% static 'js/dashboard.js' %}"></script> {% endcomment %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
    {% comment %} <script src="{% static 'js/main.js' %}"></script> {% endcomment %}
  </body>
</html>

templates/base_auth.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>InExManager  {% block title %}{% endblock %}   </title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/main.css'%}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
  </head>
  <body>

    <main role="main">



      {% block content %}

      {% endblock %}


    </main>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.4/static/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="/docs/4.4/dist/js/bootstrap.bundle.min.js" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
        <script src="{% static 'js/main.js' %}"></script></body>
</html>